/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx,js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#101415',
        'surface-dim': '#101415',
        'surface-bright': '#363a3b',
        'surface-container-lowest': '#0b0f10',
        'surface-container-low': '#191c1e',
        'surface-container': '#1d2022',
        'surface-container-high': '#272a2c',
        'surface-container-highest': '#323537',
        'on-surface': '#e0e3e5',
        'on-surface-variant': '#e6bdb9',
        'inverse-surface': '#e0e3e5',
        'inverse-on-surface': '#2d3133',
        outline: '#ac8884',
        'outline-variant': '#5c403c',
        'surface-tint': '#ffb4ac',
        primary: '#ffb4ac',
        'on-primary': '#690007',
        'primary-container': '#ff544c',
        'on-primary-container': '#5c0005',
        'inverse-primary': '#bf0617',
        secondary: '#d3fbff',
        'on-secondary': '#00363a',
        'secondary-container': '#00eefc',
        'on-secondary-container': '#00686f',
        tertiary: '#bec6e0',
        'on-tertiary': '#283044',
        'tertiary-container': '#8990a8',
        'on-tertiary-container': '#22293d',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ac',
        'on-primary-fixed': '#410002',
        'on-primary-fixed-variant': '#93000e',
        'secondary-fixed': '#7df4ff',
        'secondary-fixed-dim': '#00dbe9',
        'on-secondary-fixed': '#002022',
        'on-secondary-fixed-variant': '#004f54',
        'tertiary-fixed': '#dae2fd',
        'tertiary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed': '#131b2e',
        'on-tertiary-fixed-variant': '#3f465c',
        background: '#101415',
        'on-background': '#e0e3e5',
        'surface-variant': '#323537',
      },
      fontFamily: {
        display: ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        caption: ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '1.2', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'max-width': '1280px',
      },
      maxWidth: {
        'max-width': '1280px',
      },
      boxShadow: {
        'pixel': '0 0 0 1px #323537',
      },
    },
  },
  plugins: [],
};